import type { McpCatalogEntry } from './types.js'

export const mcpStarterCatalog: McpCatalogEntry[] = [
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Official hosted Supabase MCP for database, project, logs, Edge Functions, and docs workflows.',
    transport: 'streamable_http',
    url: 'https://mcp.supabase.com/mcp',
    authTypes: ['oauth', 'bearer', 'env'],
    defaultAuthType: 'oauth',
    docsUrl: 'https://supabase.com/docs/guides/ai-tools/mcp',
    repoUrl: 'https://github.com/supabase/mcp',
    toolsSummary: 'Database ops, logs/advisors, Edge Functions, docs search, project metadata.',
    caveat: 'Can mutate databases/projects depending scopes and server options; scope access carefully.',
    safety: 'write_capable',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Official hosted Notion MCP for workspace search and page/database updates.',
    transport: 'streamable_http',
    url: 'https://mcp.notion.com/mcp',
    authTypes: ['oauth'],
    defaultAuthType: 'oauth',
    docsUrl: 'https://developers.notion.com/docs/mcp',
    repoUrl: 'https://github.com/makenotion/notion-mcp-server',
    toolsSummary: 'Search/fetch/create/update pages, databases, comments, and users.',
    caveat: 'Workspace write access depends on granted OAuth permissions.',
    safety: 'write_capable',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Official hosted Linear MCP for issue, project, and comment workflows.',
    transport: 'streamable_http',
    url: 'https://mcp.linear.app/mcp',
    authTypes: ['oauth', 'bearer', 'env'],
    defaultAuthType: 'oauth',
    docsUrl: 'https://linear.app/docs/mcp',
    toolsSummary: 'Find, search, create, and update issues, projects, and comments.',
    caveat: 'Can mutate work items unless token/scopes are restricted.',
    safety: 'write_capable',
  },
  {
    id: 'cloudflare-docs',
    name: 'Cloudflare Docs',
    description: 'Official Cloudflare documentation MCP server for read-only docs search.',
    transport: 'streamable_http',
    url: 'https://docs.mcp.cloudflare.com/mcp',
    authTypes: ['oauth', 'none'],
    defaultAuthType: 'oauth',
    docsUrl: 'https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/',
    repoUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    toolsSummary: 'Search Cloudflare documentation.',
    caveat: 'Starter catalog intentionally uses docs search, not the broader Cloudflare API MCP.',
    safety: 'read_only',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Official hosted Sentry MCP for debugging issues, events, traces, and performance.',
    transport: 'streamable_http',
    url: 'https://mcp.sentry.dev',
    authTypes: ['oauth'],
    defaultAuthType: 'oauth',
    docsUrl: 'https://github.com/getsentry/sentry-mcp',
    repoUrl: 'https://github.com/getsentry/sentry-mcp',
    toolsSummary: 'Issue/event search and debugging workflows around errors, traces, and performance.',
    caveat: 'Scope org/project access carefully; some tools may depend on upstream Sentry permissions.',
    safety: 'mixed',
  },
]

export function catalogEntryById(id: string): McpCatalogEntry | undefined {
  return mcpStarterCatalog.find(entry => entry.id === id)
}
